-- achievement_criteria: 4 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `achievement_criteria` WHERE `id` IN (@DarkIronDwarfCritera1, @DarkIronDwarfCritera2, @DarkIronDwarfCritera3, @DarkIronDwarfCritera4);
INSERT INTO `achievement_criteria` (`id`, `achievement_id`, `type`, `req_asset_id`, `req_asset_count`, `start_event`, `start_asset_id`, `fail_event`, `fail_asset_id`, `desc_enus`, `desc_kokr`, `desc_frfr`, `desc_dede`, `desc_zhcn`, `desc_zhtw`, `desc_eses`, `desc_esmx`, `desc_ruru`, `desc_jajp`, `desc_ptpt`, `desc_itit`, `desc_unused_1`, `desc_unused_2`, `desc_unused_3`, `desc_unused_4`, `desc_flags`, `flags`, `timer_start_event`, `timer_asset_id`, `timer_limit`, `ui_order`) VALUES
(@DarkIronDwarfCriteria1, @DarkIronDwarfKnowThyEnemy, 53, @DarkIronDwarf, 1, 0, 0, 0, 0, @DarkIronDwarfenUS, @DarkIronDwarfkoKR, @DarkIronDwarffrFR, @DarkIronDwarfdeDE, @DarkIronDwarfzhCN, @DarkIronDwarfzhTW, @DarkIronDwarfesES, @DarkIronDwarfesMX, @DarkIronDwarfruRU, @DarkIronDwarfjaJP, @DarkIronDwarfptPT, @DarkIronDwarfitIT, '', '', '', '', 16712190, 0, 0, 0, 0, 6),
(@DarkIronDwarfCriteria2, @ShakeYourBunnyMaker, 110, 61815, 1, 0, 0, 0, 0, @DarkIronDwarfenUS, @DarkIronDwarfkoKR, @DarkIronDwarffrFR, @DarkIronDwarfdeDE, @DarkIronDwarfzhCN, @DarkIronDwarfzhTW, @DarkIronDwarfesES, @DarkIronDwarfesMX, @DarkIronDwarfruRU, @DarkIronDwarfjaJP, @DarkIronDwarfptPT, @DarkIronDwarfitIT, '', '', '', '', 16712190, 0, 0, 0, 0, 15),
(@DarkIronDwarfCriteria3, @CheckYourHead, 110, 44212, 1, 0, 0, 0, 0, @DarkIronDwarfenUS, @DarkIronDwarfkoKR, @DarkIronDwarffrFR, @DarkIronDwarfdeDE, @DarkIronDwarfzhCN, @DarkIronDwarfzhTW, @DarkIronDwarfesES, @DarkIronDwarfesMX, @DarkIronDwarfruRU, @DarkIronDwarfjaJP, @DarkIronDwarfptPT, @DarkIronDwarfitIT, '', '', '', '', 16712190, 0, 0, 0, 0, 15),
(@DarkIronDwarfCriteria4, @DarkIronDwarfAchievement, 5, 80, 0, 0, 0, 0, 0, @Level80AchievementDescriptionenUS, @Level80AchievementDescriptionkoKR, @Level80AchievementDescriptionfrFR, @Level80AchievementDescriptiondeDE, @Level80AchievementDescriptionzhCN, @Level80AchievementDescriptionzhTW, @Level80AchievementDescriptionesES, @Level80AchievementDescriptionesMX, @Level80AchievementDescriptionruRU, @Level80AchievementDescriptionptPT, @Level80AchievementDescriptionptBR, @Level80AchievementDescriptionitIT, '', '', '', '', 16712190, 2, 0, 0, 0, 1);
