-- faction: 0 inserts, 91 updates, 0 deletes

-- Changed values
-- Alliance-aligned
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionAlliance;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@AllianceMask & ~@GnomeMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionGnomereganExiles;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@AllianceMask & ~@DwarfMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionIronforge;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@AllianceMask & ~@NightElfMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionDarnassus;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@AllianceMask & ~@HumanMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionStormwind;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@AllianceMask & ~@DraeneiMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionExodar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionWildhammerClan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionTheLeagueofArathor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionStormpikeGuard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionSilverwingSentinels;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionAllianceForces; -- Worgoblin has these the other way around?
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionHonorHold;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionKurenai;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionAllianceVanguard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionValianceExpedition;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionExplorersLeague;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = 1082; -- REUSE? Maybe 1077: Shattered Sun Offensive?
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionWarsongOffensive;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionTheSilverCovenant;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask
                 WHERE `id` = @FactionTheFrostborn;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @AllianceMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @HordeMask,
                     `reputation_race_mask_3` = `reputation_race_mask_3` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | @HordeMask
                 WHERE `id` = @FactionKirinTor;

-- Horde-aligned
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionHorde;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@BarrensBros & ~@OrcMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | @UndercityMask
                 WHERE `id` = @FactionOrgrimmar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@BarrensBros & ~@TaurenMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | @UndercityMask
                 WHERE `id` = @FactionThunderBluff;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | (@BarrensBros & ~@TrollMask),
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | @UndercityMask
                 WHERE `id` = @FactionDarkspearTrolls;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @BarrensBros,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | (@UndercityMask & ~@UndeadMask)
                 WHERE `id` = @FactionUndercity;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @BarrensBros,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask,
                     `reputation_race_mask_4` = `reputation_race_mask_4` | (@UndercityMask & ~@BloodElfMask)
                 WHERE `id` = @FactionSilvermoonCity;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTheDefilers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionWintersaberTrainers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionCenarionCircle;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionFrostwolfClan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionWarsongOutriders;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionHordeForces;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTranquillien;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTheMaghar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionThrallmar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionHordeExpedition;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTheTaunka;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTheHandofVengeance;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @HordeMask,
                     `reputation_race_mask_2` = `reputation_race_mask_2` | @AllianceMask
                 WHERE `id` = @FactionTheSunreavers;

-- Everyone
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBootyBay;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBlacksmithingArmorsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionThoriumBrotherhood;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionSyndicate;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionLeatherworkingElemental;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionLeatherworkingDragonscale;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBloodsailBuccaneers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionGelkisClanCentaur;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionMagramClanCentaur;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionSteamwheedleCartel;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionZandalarTribe;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBlacksmithingWeaponsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionRavenholdt;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionGadgetzan;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionRatchet;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionArgentDawn;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionLeatherworkingTribal;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionEngineeringGoblin;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionEngineeringGnome;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBlacksmithingHammersmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBlacksmithingAxesmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBlacksmithingSwordsmithing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionCaerDarrow;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTimbermawHold;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionEverlook;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionHydraxianWaterlords;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionShendralar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionDarkmoonFaire;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionBroodofNozdormu;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheAldor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheConsortium;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheScryers;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheShatar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionShattrathCity;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionCenarionExpedition;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionSporeggar;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionKeepersofTime;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheScaleoftheSands;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionAshtongueDeathsworn;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionNetherwing;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionShatariSkyguard;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionOgrila;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheKaluak;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheWyrmrestAccord;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionFrenzyheartTribe;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheOracles;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionSholazarBasin;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionClassic;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheSonsofHodir;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheAldor;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @PlayableRaceMask
                 WHERE `id` = @FactionTheScryers;
